"""用固定合成数据生成可审计的 TUI 文档 SVG。

资产直接调用生产 TUI 的 ``_draw_*`` 函数，不启动真实终端，不读取用户目录，
也不连接 Docker、File Provider 或网络服务。
"""
from __future__ import annotations

import argparse
import html
import sys
import unicodedata
import xml.etree.ElementTree as ET
from pathlib import Path
from unittest import mock

IMPLEMENTATION_ROOT = Path(__file__).resolve().parents[1]
if str(IMPLEMENTATION_ROOT) not in sys.path:
    sys.path.insert(0, str(IMPLEMENTATION_ROOT))

REPOSITORY_ROOT = IMPLEMENTATION_ROOT.parent
DEFAULT_OUTPUT_DIR = REPOSITORY_ROOT / "docs" / "assets"
ASSET_NAMES = (
    "tui-clean-review.svg",
    "tui-clean-confirm.svg",
    "tui-analyze.svg",
)
TERMINAL_HEIGHT = 24
TERMINAL_WIDTH = 120
CELL_WIDTH = 10
CELL_HEIGHT = 22
LEFT_MARGIN = 24
TOP_MARGIN = 58


def _cell_width(character: str) -> int:
    if unicodedata.combining(character):
        return 0
    return 2 if unicodedata.east_asian_width(character) in {"W", "F"} else 1


class GridScreen:
    """实现 TUI 绘制函数所需的最小、位置感知 screen 协议。"""

    def __init__(
        self,
        height: int = TERMINAL_HEIGHT,
        width: int = TERMINAL_WIDTH,
    ) -> None:
        self.height = height
        self.width = width
        self.keypad_enabled = False
        self.erase()

    def keypad(self, enabled: bool) -> None:
        self.keypad_enabled = enabled

    def getmaxyx(self) -> tuple[int, int]:
        return self.height, self.width

    def erase(self) -> None:
        self.cells: list[list[str | None]] = [
            [None for _ in range(self.width)]
            for _ in range(self.height)
        ]

    def addnstr(
        self,
        row: int,
        column: int,
        text: str,
        length: int,
    ) -> None:
        if not 0 <= row < self.height or column < 0 or column >= self.width:
            return
        limit = min(self.width - 1, column + max(0, length))
        cursor = column
        previous: int | None = None
        for character in text:
            width = _cell_width(character)
            if width == 0:
                if previous is not None and self.cells[row][previous]:
                    self.cells[row][previous] += character
                continue
            if cursor + width > limit:
                break
            self.cells[row][cursor] = character
            previous = cursor
            for continuation in range(1, width):
                self.cells[row][cursor + continuation] = ""
            cursor += width

    def refresh(self) -> None:
        pass

    def getch(self) -> int:
        raise RuntimeError("文档资产捕获不会读取键盘")

    def plain_text(self) -> str:
        lines = []
        for row in self.cells:
            line = "".join(cell if cell is not None else " " for cell in row)
            lines.append(line.rstrip())
        return "\n".join(lines).rstrip()


def _svg(screen: GridScreen, *, title: str, description: str) -> str:
    width = LEFT_MARGIN * 2 + screen.width * CELL_WIDTH
    height = TOP_MARGIN + screen.height * CELL_HEIGHT + 24
    accessible_description = f"{description}\n\n{screen.plain_text()}"
    elements: list[str] = [
        '<!-- Generated by implementation/scripts/capture_tui_assets.py. -->',
        (
            f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" '
            f'height="{height}" viewBox="0 0 {width} {height}">'
        ),
        f"  <title>{html.escape(title)}</title>",
        f"  <desc>{html.escape(accessible_description)}</desc>",
        (
            f'  <rect width="{width}" height="{height}" rx="16" '
            'fill="#0d1117"/>'
        ),
        (
            f'  <rect width="{width}" height="44" rx="16" '
            'fill="#161b22"/>'
        ),
        '  <rect y="28" width="100%" height="16" fill="#161b22"/>',
        '  <circle cx="22" cy="22" r="6" fill="#ff5f57"/>',
        '  <circle cx="42" cy="22" r="6" fill="#febc2e"/>',
        '  <circle cx="62" cy="22" r="6" fill="#28c840"/>',
        (
            f'  <text x="{width / 2:.1f}" y="27" text-anchor="middle" '
            'fill="#8b949e" font-family="Menlo, Monaco, monospace" '
            f'font-size="14">{html.escape(title)}</text>'
        ),
        (
            '  <g fill="#c9d1d9" '
            'font-family="Menlo, Monaco, Noto Sans Mono CJK SC, monospace" '
            'font-size="15">'
        ),
    ]
    for row_index, row in enumerate(screen.cells):
        baseline = TOP_MARGIN + (row_index + 1) * CELL_HEIGHT - 5
        for column, character in enumerate(row):
            if character in {None, "", " "}:
                continue
            x = LEFT_MARGIN + column * CELL_WIDTH
            elements.append(
                f'    <text x="{x}" y="{baseline}">'
                f"{html.escape(character)}</text>"
            )
    elements.extend(("  </g>", "</svg>", ""))
    return "\n".join(elements)


def _clean_items():
    from openclean.models import Item

    return (
        Item(
            path=Path("/tmp/openclean-demo/pip"),
            size=5_400_000_000,
            category="pip / uv caches",
            safety="safe",
            preselected=True,
            domain="developer",
        ),
        Item(
            path=Path("/tmp/openclean-demo/homebrew"),
            size=1_700_000_000,
            category="Homebrew downloads",
            safety="safe",
            preselected=True,
            domain="developer",
        ),
        Item(
            path=Path("/tmp/openclean-demo/custom-cache"),
            size=860_000_000,
            category="环境变量缓存",
            safety="confirm",
            preselected=False,
            domain="developer",
            requires_explicit_selection=True,
        ),
        Item(
            path=None,
            size=12_800_000_000,
            category="Docker Local Volumes",
            safety="critical",
            preselected=False,
            domain="developer",
            actionable=False,
            action_block_reason="Local Volumes 永远拒绝 prune",
            resource_kind="docker",
            identifier="docker:volumes",
        ),
    )


def _render_clean_review() -> str:
    from openclean.tui import ReviewGroup, _draw_items, _item_key

    items = _clean_items()
    groups = (ReviewGroup("developer", "Dev Tools", items),)
    selected = {_item_key(item) for item in items if item.preselected}
    screen = GridScreen()
    _draw_items(
        screen,
        groups,
        group_index=0,
        cursor=2,
        selected_keys=selected,
        title="Clean · 扫描结果",
    )
    return _svg(
        screen,
        title="Clean TUI · 候选审阅",
        description=(
            "生产 Clean TUI 绘制逻辑使用固定合成候选生成的安全审阅画面。"
        ),
    )


def _render_clean_confirmation() -> str:
    from openclean.tui import ReviewGroup, _draw_confirmation, _item_key

    items = _clean_items()
    groups = (ReviewGroup("developer", "Dev Tools", items),)
    selected = {_item_key(item) for item in items if item.preselected}
    screen = GridScreen()
    _draw_confirmation(
        screen,
        groups,
        selected,
        title="Clean · 扫描结果",
        allow_execution=False,
    )
    return _svg(
        screen,
        title="Clean TUI · 只读汇总",
        description=(
            "未指定 --yes 时，生产 Clean TUI 明确说明只输出选择预览。"
        ),
    )


def _render_analyze() -> str:
    from openclean.analyzer import SpaceAnalysis, SpaceEntry
    from openclean.models import Item
    from openclean.space_tui import _draw_browser

    root = Path("/tmp/openclean-demo/space")
    items = (
        Item(
            path=root / "Projects",
            size=31_000_000_000,
            category="空间占用",
            safety="confirm",
            domain="analyze",
        ),
        Item(
            path=root / "Caches",
            size=13_500_000_000,
            category="空间占用",
            safety="confirm",
            domain="analyze",
        ),
        Item(
            path=root / "Archives",
            size=7_800_000_000,
            category="空间占用",
            safety="confirm",
            domain="analyze",
        ),
        Item(
            path=root / "Cloud-Placeholder",
            size=0,
            category="空间占用",
            safety="critical",
            domain="analyze",
            actionable=False,
            action_block_reason="dataless/疑似云占位",
            is_cloud_file=True,
            cloud_file_count=12,
        ),
        Item(
            path=root / "Logs",
            size=1_200_000_000,
            category="空间占用",
            safety="confirm",
            domain="analyze",
        ),
    )
    total = sum(item.size for item in items)
    entries = [
        SpaceEntry(item=item, percent=(item.size / total * 100 if total else 0))
        for item in items
    ]
    analysis = SpaceAnalysis(
        root=root,
        entries=entries,
        volume_total=1_000_000_000_000,
        volume_free=420_000_000_000,
        local_snapshots_checked=False,
    )
    selected = {items[1].path: items[1]}
    directories = {items[0].path, items[1].path, items[2].path}
    screen = GridScreen()
    with mock.patch(
        "openclean.space_tui._is_directory",
        side_effect=lambda path: path in directories,
    ):
        _draw_browser(
            screen,
            analysis,
            entries[:4],
            cursor=1,
            selected=selected,
            message="纯浏览不会修改文件；当前画面只使用固定合成数据。",
        )
    return _svg(
        screen,
        title="Analyze TUI · 空间浏览",
        description=(
            "生产 Analyze TUI 绘制逻辑使用固定合成目录生成的空间浏览画面。"
        ),
    )


def render_assets() -> dict[str, str]:
    assets = {
        "tui-clean-review.svg": _render_clean_review(),
        "tui-clean-confirm.svg": _render_clean_confirmation(),
        "tui-analyze.svg": _render_analyze(),
    }
    if tuple(assets) != ASSET_NAMES:
        raise AssertionError("TUI 资产名称与清单不一致")
    forbidden = (
        "/Users/",
        "/Volumes/",
        "file://",
        "<script",
        "<foreignObject",
        "href=",
    )
    for name, content in assets.items():
        ET.fromstring(content)
        lowered = content.lower()
        for marker in forbidden:
            if marker.lower() in lowered:
                raise ValueError(f"{name} 包含禁止内容：{marker}")
    return assets


def _write_assets(output_dir: Path, assets: dict[str, str]) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    for name, content in assets.items():
        (output_dir / name).write_text(content, encoding="utf-8")
        print(f"wrote {output_dir / name}")


def _check_assets(output_dir: Path, assets: dict[str, str]) -> int:
    stale = []
    for name, content in assets.items():
        path = output_dir / name
        if not path.is_file() or path.read_text(encoding="utf-8") != content:
            stale.append(name)
    extras = sorted(
        path.name
        for path in output_dir.glob("tui-*.svg")
        if path.name not in assets
    ) if output_dir.is_dir() else []
    if stale or extras:
        if stale:
            print(
                "TUI 文档资产缺失或过期：" + ", ".join(stale),
                file=sys.stderr,
            )
        if extras:
            print("存在未管理的 TUI 资产：" + ", ".join(extras), file=sys.stderr)
        print(
            "运行 python3 implementation/scripts/capture_tui_assets.py --write",
            file=sys.stderr,
        )
        return 1
    print(f"TUI 文档资产：PASS（{len(assets)} 个确定性 SVG）")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="生成或核对生产 TUI 的合成文档 SVG",
    )
    action = parser.add_mutually_exclusive_group(required=True)
    action.add_argument("--write", action="store_true", help="写入/更新资产")
    action.add_argument("--check", action="store_true", help="只读核对资产")
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help=f"输出目录；默认 {DEFAULT_OUTPUT_DIR}",
    )
    args = parser.parse_args(argv)
    assets = render_assets()
    if args.write:
        _write_assets(args.output, assets)
        return 0
    return _check_assets(args.output, assets)


if __name__ == "__main__":
    raise SystemExit(main())
